# Generated by Django 4.0.3 on 2022-03-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilelink',
            name='link',
            field=models.URLField(default='My link', null=True),
        ),
    ]
