# Generated by Django 4.0.3 on 2022-03-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_contact_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='summary',
            field=models.CharField(choices=[('Registration', 'Registration'), ('Profile Avatar', 'Profile Avatar'), ('Profile Settings', 'Profile Settings'), ('Another', 'Another')], max_length=25),
        ),
        migrations.AlterField(
            model_name='contact',
            name='topic',
            field=models.TextField(max_length=200),
        ),
    ]
