# Generated by Django 4.0.3 on 2022-03-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_contact_summary_alter_contact_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilelink',
            name='link',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profilelink',
            name='link_name',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
