# Generated by Django 4.0.3 on 2022-03-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verif',
            field=models.BooleanField(default=False),
        ),
    ]
