# Generated by Django 4.0.3 on 2022-06-11 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_profile_verif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='summary',
            field=models.CharField(choices=[('Registration', 'Registration'), ('Profile Avatar', 'Profile Avatar'), ('Profile Settings', 'Profile Settings'), ('Another', 'Another'), ('Request for API', 'Request for API')], max_length=25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
