# Generated by Django 4.0.3 on 2022-09-05 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_contact_summary_alter_profile_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_name', models.CharField(blank=True, default='main stack: Django', help_text='what was your main stack', max_length=20, null=True)),
                ('project_name', models.CharField(blank=True, default='my project name', help_text='your project name', max_length=25, null=True)),
                ('project_link', models.CharField(max_length=200, null=True)),
                ('project_description', models.TextField(blank=True, default='summary about your project', help_text='pitch the main part of your project', max_length=100, null=True)),
                ('project_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.profile')),
            ],
            options={
                'verbose_name': 'Projects',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
