# Generated by Django 4.0.3 on 2022-12-14 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_blog_projects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['-project_date'], 'verbose_name': 'Projects', 'verbose_name_plural': 'Projects'},
        ),
    ]
